# Generated by Django 3.2.9 on 2021-11-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='icecreams',
            options={'managed': False, 'verbose_name': 'Мороженное', 'verbose_name_plural': 'Мороженное'},
        ),
    ]
