# Generated by Django 4.0 on 2021-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'pc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('frequency', models.IntegerField()),
                ('memory_cash', models.IntegerField()),
            ],
            options={
                'db_table': 'processor',
                'managed': False,
            },
        ),
    ]
