# Generated by Django 4.0 on 2021-12-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RK2_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={},
        ),
    ]
