# Generated by Django 4.0 on 2021-12-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RK2_App', '0002_alter_pc_options_alter_processor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='id_processor',
            field=models.ForeignKey(blank=True, db_column='id_processor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RK2_App.processor'),
        ),
    ]
